# Generated by Django 5.2.10 on 2026-03-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_challenge_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
