# Generated by Django 5.2.10 on 2026-03-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_challenge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='achievement',
            field=models.ManyToManyField(blank=True, related_name='challenges', to='core.achievement'),
        ),
    ]
